#!/usr/bin/env bash

# -----------------------------------
# Colors
GREEN=$'\e[0;32m'
YELLOW=$'\e[1;33m'
BLUE=$'\e[0;34m'
RED=$'\e[0;31m'
NC=$'\e[0m'
# -----------------------------------
export CURRENT_SHELL=$(basename "$SHELL")

# Init main directory
if [ -z "${PROJECT_ROOT}" ]; then
    export PROJECT_ROOT="$(dirname "$(realpath $0)")"
fi

# Help commands
_help() {
    if [ ! -f "${PROJECT_ROOT}/.env" ]; then
        echo "
${YELLOW}Usage:${NC}
    ${GREEN}dbvisor-agent [command]${NC}

${YELLOW}Options:${NC}
    ${GREEN}-l | --list${NC}  - list of available commands

${YELLOW}Available Commands:${NC}
    ${RED}setup${NC}          - initial setup
"
    else
        echo "
${YELLOW}Usage:${NC}
    ${GREEN}dbvisor-agent [command]${NC}

${YELLOW}Options:${NC}
    ${GREEN}-l | --list${NC}  - list of available commands

${YELLOW}Available Commands:${NC}
    ${GREEN}start${NC}      - start environment ( Docker only )
    ${GREEN}stop${NC}       - stop environment ( Docker only )
    ${GREEN}stopall${NC}    - stop all environment ( Docker only )
    ${GREEN}re-build${NC}   - re-bild containers ( Docker only )
    ${GREEN}cli${NC}        - allows to run command line command inside of docker environment ( Docker only )
    ${GREEN}composer${NC}   - run composer commands ( Docker only )
    ${GREEN}mysql${NC}      - run mysql command ( Docker only )
    ${GREEN}console${NC}    - run app console commands
    ${GREEN}cron${NC}       - run con commands ( Docker only )
    ${GREEN}info${NC}       - basic information about tool

    ${RED}setup${NC}        - initial setup

${YELLOW}Tool:${NC}
    ${GREEN}app:server:add${NC}         - Start adding the server to service
                            ${BLUE}--email[=EMAIL]${NC} Email to authorize
                            ${BLUE}--password[=PASSWORD]${NC} Password to authorize
                            ${BLUE}--current${NC} If this option set it command only updates server credentials
    ${GREEN}app:server:update${NC}      - Update the server data
                            ${BLUE}--email[=EMAIL]${NC} Email to authorize
                            ${BLUE}--password[=PASSWORD]${NC} Password to authorize
                            ${BLUE}--current${NC} If this option set it command only updates server credentials
    ${GREEN}app:db:process${NC}         - Start processing scheduled database
    ${GREEN}app:db:analyze${NC}         - Start analyzing db structure
                            ${RED}-u | --uid[=UID]${NC} Database UUID from the service
                            ${BLUE}--db[=DB]${NC} Database Name
    ${GREEN}app:db:add${NC}             - Create DB dump
                            ${RED}--db[=DB]${NC} Database Name
                            ${BLUE}--path[=PATH]${NC} Full path to backup file
                            ${BLUE}--engine[=ENGINE]${NC} Db Engine ( mysql | postgres ). Default: mysql
    ${GREEN}app:db:backups:clear${NC}   - Start cleaning old DB backups
    ${GREEN}app:cron:install${NC}       - Generates and installs crontab for current user
"
    fi
}

# Tool information
_info() {
    echo "
    Tool is installed in dir:   ${GREEN}${PROJECT_ROOT}${NC}
    Main config file is:        ${GREEN}${PROJECT_ROOT}/.env${NC}"

    if [ -f "${PROJECT_ROOT}/.env.mysql" ]; then
        echo "
    MySQL config file is:       ${GREEN}${PROJECT_ROOT}/.env.mysql${NC}
    "
    fi

    if [ -f "${PROJECT_ROOT}/.env.postgress" ]; then
        echo "
    Postgress config file is:   ${GREEN}${PROJECT_ROOT}/.env.postgress${NC}
    "
    fi
}

# Get configurations
if [ ! -f "${PROJECT_ROOT}/.env" ]; then
    case "$1" in
        setup)
            . "${PROJECT_ROOT}"/bin/setup
            ;;
        *)
            _help
            ;;
    esac

    exit 1
fi

export $(cat "${PROJECT_ROOT}/.env" | grep -v ^# | grep -v ^alias | xargs)

# Check is docker been started
_checkDocker() {
    if [[ -z $(docker container ls -q --filter "name=${IMAGES_PREFIX:-}dbvisor-server") ]]; then
        echo "You must start docker instance before continue."

        exit 1
    fi
}

if [ ${1} = '-l' ] || [ ${1} = '--list' ]; then
    _help
    exit 1
elif [ "${1}" = 'setup' ]; then
    . "${PROJECT_ROOT}"/bin/setup
else
    if [ "${APP_DOCKER_USE}" = "1" ]; then
        case "$1" in
            start)
                . "${PROJECT_ROOT}"/bin/docker/start "${@:2}"
                ;;
            stop)
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/stop
                ;;
            start-db)
                . "${PROJECT_ROOT}"/bin/docker/start-db "${@:2}"
                ;;
            stop-db)
                . "${PROJECT_ROOT}"/bin/docker/stop-db "${@:2}"
                ;;
            stopall)
                . "${PROJECT_ROOT}"/bin/docker/stopall
                ;;
            re-build)
                . "${PROJECT_ROOT}"/bin/docker/re-build
                ;;
            console)
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/console "${@:2}"
                ;;
            composer)
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/composer "${@:2}"
                ;;
            cli)
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/cli "${@:2}"
                ;;
            cron)
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/cron "${@:2}"
                ;;
            app:server:add)
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/console "app:server:add" "${@:2}"
                ;;
            app:server:update)
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/console "app:server:update" "${@:2}"
                ;;
            app:db:process)
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/console "app:db:process"
                ;;
            app:db:add)
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/console "app:db:add" "${@:2}"
                ;;
            app:db:analyze)
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/console "app:db:analyze" "${@:2}"
                ;;
            app:cron:install)
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/cron setup
                ;;
            info)
                _info
                ;;
            *)
                _help
                ;;
        esac
    else
        case "$1" in
            console)
                php "${PROJECT_ROOT}"/bin/console "${@:2}"
                ;;
            app:server:add)
                php "${PROJECT_ROOT}"/bin/console "app:server:add" "${@:2}"
                ;;
            app:server:update)
                php "${PROJECT_ROOT}"/bin/console "app:server:update" "${@:2}"
                ;;
            app:db:process)
                php "${PROJECT_ROOT}"/bin/console "app:db:process"
                ;;
            app:db:add)
                php "${PROJECT_ROOT}"/bin/console "app:db:add" "${@:2}"
                ;;
            app:cron:install)
                php "${PROJECT_ROOT}"/bin/console "app:cron:install"
                ;;
            app:db:analyze)
                php "${PROJECT_ROOT}"/bin/console "app:db:analyze" "${@:2}"
                ;;
            info)
                _info
                ;;
            *)
                _help
                ;;
        esac
    fi
fi
