#!/bin/sh

# -----------------------------------
# Colors
GREEN='\e[0;32m'
YELLOW='\e[1;33m'
BLUE='\e[0;34m'
RED='\e[0;31m'
NC='\e[0m'
# -----------------------------------
export CURRENT_SHELL=$(basename "$SHELL")

# Init main directory
if [ -z "${PROJECT_ROOT}" ]; then
    export PROJECT_ROOT="$(dirname "$(realpath $0)")"
fi

# Help commands
_help() {
    if [ ! -f "${PROJECT_ROOT}/.env" ]; then
        # shellcheck disable=SC2059
        printf "
${YELLOW}Usage:${NC}
    ${GREEN}dbvisor-agent [command]${NC}

${YELLOW}Options:${NC}
    ${GREEN}-l | --list${NC}  - list of available commands

${YELLOW}Available Commands:${NC}
    ${RED}setup${NC}        - initial setup
"
    else
        # shellcheck disable=SC2059
        printf "
${YELLOW}Usage:${NC}
    ${GREEN}dbvisor-agent [command]${NC}

${YELLOW}Options:${NC}
    ${GREEN}-l | --list${NC}  - list of available commands
"

# shellcheck disable=SC2059
printf "
${YELLOW}Available Commands:${NC}
    ${GREEN}start${NC}      - start environment ( Docker only )
    ${GREEN}stop${NC}       - stop environment ( Docker only )
    ${GREEN}stopall${NC}    - stop all environment ( Docker only )
    ${GREEN}re-build${NC}   - re-build containers ( Docker only )
    ${GREEN}cli${NC}        - allows to run command line command inside of docker environment ( Docker only )
    ${GREEN}console${NC}    - run app console commands
    ${GREEN}cron${NC}       - run con commands ( Docker only )
    ${GREEN}info${NC}       - basic information about tool

    ${RED}setup${NC}      - initial setup
"

# shellcheck disable=SC2059
printf "
${YELLOW}Tool:${NC}
    ${GREEN}app:server:add${NC}                 - Start adding the server to service
                                      ${BLUE}--email[=EMAIL]${NC} Email to authorize
                                      ${BLUE}--password[=PASSWORD]${NC} Password to authorize
                                      ${BLUE}--current${NC} If this option set it command only updates server credentials
    ${GREEN}app:server:update${NC}              - Update the server data
                                      ${BLUE}--email[=EMAIL]${NC} Email to authorize
                                      ${BLUE}--password[=PASSWORD]${NC} Password to authorize
                                      ${BLUE}--current${NC} If this option set it command only updates server credentials
    ${GREEN}app:server:generate-keypair${NC}    - Generate public/private keys for use in your application.
                                      ${BLUE}--identifier[=EMAIL]${NC} User identifier!
    ${GREEN}app:db:process${NC}                 - Start processing scheduled database
    ${GREEN}app:db:analyze${NC}                 - Start analyzing db structure
                                      ${RED}-u | --uid[=UID]${NC} Database UUID from the service
                                      ${BLUE}--db[=DB]${NC} Database Name
    ${GREEN}app:db:add${NC}                     - Create DB dump
                                      ${RED}--db[=DB]${NC} Database Name
                                      ${BLUE}--path[=PATH]${NC} Full path to backup file
                                      ${BLUE}--engine[=ENGINE]${NC} Db Engine ( mysql | postgres ). Default: mysql
    ${GREEN}app:db:update${NC}                  - Update DB dump
                                      ${BLUE}-u | --uid[=UID]${NC} Database Uid
    ${GREEN}app:db:backups:clear${NC}           - Start cleaning old DB backups
    ${GREEN}app:cron:install${NC}               - Generates and installs crontab for current user
"
    fi
}

# Tool information
_info() {
    # shellcheck disable=SC2059
    printf "${YELLOW}Tool Configurations:${NC}
    Tool is installed in dir:   ${GREEN}${PROJECT_ROOT}${NC}
    Main config file is:        ${GREEN}${PROJECT_ROOT}/.env${NC}
"

    if [ -f "${PROJECT_ROOT}/.env.mysql" ]; then
        # shellcheck disable=SC2059
        printf "
    MySQL config file is:       ${GREEN}${PROJECT_ROOT}/.env.mysql${NC}
"
    fi

    if [ -f "${PROJECT_ROOT}/.env.postgress" ]; then
        # shellcheck disable=SC2059
        printf "
    Postgress config file is:   ${GREEN}${PROJECT_ROOT}/.env.postgress${NC}
"
    fi

    if [ "${APP_DOCKER_USE}" = "1" ]; then
        SECRET_KEY_PUBLIC=${PROJECT_ROOT}/config/keys/public
    fi

    if [ -f "${SECRET_KEY_PUBLIC}" ]; then
        data=$(grep -w 'server' ${SECRET_KEY_PUBLIC} | cut -d ":" -f2)
        printf "\n${YELLOW}Server Public Key:${NC}
-----BEGIN PUBLIC KEY-----
$data
-----END PUBLIC KEY-----
"
    fi
}

# Get configurations
if [ ! -f "${PROJECT_ROOT}/.env" ]; then
    case "$1" in
        setup)
            . "${PROJECT_ROOT}"/bin/setup
            ;;
        *)
            _help
            ;;
    esac

    exit 1
fi

export $(cat "${PROJECT_ROOT}/.env" | grep -v ^# | grep -v ^alias | xargs)

# Check is docker been started
_checkDocker() {
    if [ -z $(docker container ls -q --filter "name=${IMAGES_PREFIX:-}dbvisor-server") ]; then
        echo "You must start docker instance before continue."

        exit 1
    fi
}

if [ "${1}" = '-l' ] || [ "${1}" = '--list' ]; then
    _help
    exit 1
elif [ "${1}" = 'setup' ]; then
    . "${PROJECT_ROOT}"/bin/setup
else
    command=$1
    if [ "${APP_DOCKER_USE}" = "1" ]; then
        case "$command" in
            start)
                shift $(( 1 > $# ? $# : 1))
                . "${PROJECT_ROOT}"/bin/docker/start "${@}"
                ;;
            stop)
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/stop
                ;;
            start-db)
                shift $(( 1 > $# ? $# : 1))
                . "${PROJECT_ROOT}"/bin/docker/start-db "${@}"
                ;;
            stop-db)
                shift $(( 1 > $# ? $# : 1))
                . "${PROJECT_ROOT}"/bin/docker/stop-db "${@}"
                ;;
            stopall)
                . "${PROJECT_ROOT}"/bin/docker/stopall
                ;;
            re-build)
                . "${PROJECT_ROOT}"/bin/docker/re-build
                ;;
            console)
                shift $(( 1 > $# ? $# : 1))
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/console "${@}"
                ;;
            cli)
                shift $(( 1 > $# ? $# : 1))
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/cli "${@}"
                ;;
            cron)
                shift $(( 1 > $# ? $# : 1))
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/cron "${@}"
                ;;
            app:server:add)
                [ "${CURRENT_SHELL}" = "" ] && shift $(( 1 > $# ? $# : 1))
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/console "app:server:add" "${@}"
                ;;
            app:server:update)
                [ "${CURRENT_SHELL}" = "" ] && shift $(( 1 > $# ? $# : 1))
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/console "app:server:update" "${@}"
                ;;
            app:server:generate-keypair)
                [ "${CURRENT_SHELL}" = "" ] && shift $(( 1 > $# ? $# : 1))
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/console "app:server:generate-keypair" "${@}"
                ;;
            app:db:process)
                [ "${CURRENT_SHELL}" = "" ] && shift $(( 1 > $# ? $# : 1))
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/console "app:db:process"
                ;;
            app:db:add)
                [ "${CURRENT_SHELL}" = "" ] && shift $(( 1 > $# ? $# : 1))
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/console "app:db:add" "${@}"
                ;;
            app:db:update)
                [ "${CURRENT_SHELL}" = "" ] && shift $(( 1 > $# ? $# : 1))
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/console "app:db:update" "${@}"
                ;;
            app:db:analyze)
                [ "${CURRENT_SHELL}" = "" ] && shift $(( 1 > $# ? $# : 1))
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/console "app:db:analyze" "${@}"
                ;;
            app:cron:install)
                _checkDocker
                . "${PROJECT_ROOT}"/bin/docker/cron setup
                ;;
            info)
                _info
                ;;
            *)
                _help
                ;;
        esac
    else
        command=$1
        case "$command" in
            console)
                shift $(( 1 > $# ? $# : 1))
                php "${PROJECT_ROOT}"/bin/console "${@}"
                ;;
            app:server:add)
                [ "${CURRENT_SHELL}" = "" ] && shift $(( 1 > $# ? $# : 1))
                php "${PROJECT_ROOT}"/bin/console "app:server:add" "${@}"
                ;;
            app:server:update)
                [ "${CURRENT_SHELL}" = "" ] && shift $(( 1 > $# ? $# : 1))
                php "${PROJECT_ROOT}"/bin/console "app:server:update" "${@}"
                ;;
            app:server:generate-keypair)
                [ "${CURRENT_SHELL}" = "" ] && shift $(( 1 > $# ? $# : 1))
                php "${PROJECT_ROOT}"/bin/docker/console "app:server:generate-keypair" "${@}"
                ;;
            app:db:process)
                [ "${CURRENT_SHELL}" = "" ] && shift $(( 1 > $# ? $# : 1))
                php "${PROJECT_ROOT}"/bin/console "app:db:process"
                ;;
            app:db:add)
                [ "${CURRENT_SHELL}" = "" ] && shift $(( 1 > $# ? $# : 1))
                php "${PROJECT_ROOT}"/bin/console "app:db:add" "${@}"
                ;;
            app:db:update)
                [ "${CURRENT_SHELL}" = "" ] && shift $(( 1 > $# ? $# : 1))
                php "${PROJECT_ROOT}"/bin/console "app:db:update" "${@}"
                ;;
            app:cron:install)
                [ "${CURRENT_SHELL}" = "" ] && shift $(( 1 > $# ? $# : 1))
                php "${PROJECT_ROOT}"/bin/console "app:cron:install"
                ;;
            app:db:analyze)
                [ "${CURRENT_SHELL}" = "" ] && shift $(( 1 > $# ? $# : 1))
                php "${PROJECT_ROOT}"/bin/console "app:db:analyze" "${@}"
                ;;
            info)
                _info
                ;;
            *)
                _help
                ;;
        esac
    fi
fi
