#!/bin/bash

set -euo pipefail

app_download_url="http://db-manager-cli.bridge2.digital/download/db-server-manager.zip"
app_name="server-manager"
app_dir=".server-manager"
app_bin_path="$HOME/$app_dir/bin"

function output {
    style_start=""
    style_end=""
    if [ "${2:-}" != "" ]; then
    case $2 in
        "success")
            style_start="\033[0;32m"
            style_end="\033[0m"
            ;;
        "error")
            style_start="\033[31;31m"
            style_end="\033[0m"
            ;;
        "info"|"warning")
            style_start="\033[33m"
            style_end="\033[39m"
            ;;
        "heading")
            style_start="\033[1;33m"
            style_end="\033[22;39m"
            ;;
        "comment")
            style_start="\033[2m"
            style_end="\033[22;39m"
            ;;
    esac
    fi

    builtin echo -e "${style_start}${1}${style_end}"
}

function exit_with_error() {
    output "+--------------------------------------------------+" "error"
    output "|                                                  |" "error"
    output "|              Installation failed                 |" "error"
    output "|                                                  |" "error"
    output "+--------------------------------------------------+" "error"

    exit 1
}

function intro() {
    output "+--------------------------------------------------+" "heading"
    output "|                                                  |" "heading"
    output "|           DB Manager Server Installer            |" "heading"
    output "|                                                  |" "heading"
    output "+--------------------------------------------------+" "heading"

    output "\nChecking environment" "heading"
}

function outro() {
    output ""
    output "+--------------------------------------------------+" "success"
    output "|                                                  |" "success"
    output "| DB Manager CLI has been installed successfully.  |" "success"
    output "|                                                  |" "success"
    output "+--------------------------------------------------+" "success"

    output "\nThank you for using DB Manager!"
}

intro
mkdir -p "$app_bin_path"
curl "$app_download_url" -o /tmp/"$app_name"-tmp.zip && unzip -o /tmp/server-manager-tmp.zip -d "$app_bin_path"
"$app_bin_path"/server-manager setup
outro