#!/usr/bin/env bash

# -----------------------------------
# Colors
GREEN=$'\e[0;32m'
RED=$'\e[0;31m'
NC=$'\e[0m'
# -----------------------------------

# Init main directory
if [ -z "${MANAGER_DIR}" ]; then
    MANAGER_DIR="$(dirname "$(realpath $0)")"
fi

# Help commands
_help() {
    if [ ! -f "${MANAGER_DIR}/.env" ]; then
        echo "
Usage:
    ${GREEN}server-manager [command]${NC}

Options:
    ${GREEN}-l|--list${NC}  - list of available commands

Available Commands:
    ${RED}setup${NC}      - initial setup

Tool:
    ${GREEN}app:server:add${NC}    - Start adding the server to service
    ${GREEN}app:db:process${NC}    - Start processing database by database id and temporary database name
"
    else
        echo "
Usage:
    ${GREEN}server-manager [command]${NC}

Options:
    ${GREEN}-l|--list${NC}  - list of available commands

Available Commands:
    ${GREEN}start${NC}      - start environment
    ${GREEN}stop${NC}       - stop environment
    ${GREEN}cli${NC}        - allows to run command line command inside of docker environment
    ${GREEN}composer${NC}   - run composer commands
    ${GREEN}mysql${NC}      - run mysql command
    ${GREEN}console${NC}    - run application commands

    ${RED}setup${NC}      - initial setup

Tool:
    ${GREEN}app:server:add${NC}    - Start adding the server to service
    ${GREEN}app:db:process${NC}    - Start processing database by database id and temporary database name
"
    fi
}

# Get configurations
if [ ! -f "${MANAGER_DIR}/.env" ]; then
    case "$1" in
        setup)
            . "${MANAGER_DIR}"/bin/setup
            ;;
        *)
            _help
            ;;
    esac

    exit 1
fi

export $(cat "${MANAGER_DIR}/.env" | grep -v ^# | grep -v ^alias | xargs)

# Check is docker been started
_checkDocker() {
    if [[ -z $(docker container ls -q --filter "name=${IMAGES_PREFIX:-}app-server") ]]; then
        echo "You must start docker instance before continue."

        exit 1
    fi
}

if [[ ${1} == '-l' || ${1} == '--list' ]]; then
    _help
    exit 1
elif [ "${1}" == 'setup' ]; then
    . "${MANAGER_DIR}"/bin/setup
else
    if [ "${APP_DOCKER_USE}" == "1" ]; then
        case "$1" in
            start)
                . "${MANAGER_DIR}"/bin/docker/start
                ;;
            stop)
                _checkDocker
                . "${MANAGER_DIR}"/bin/docker/stop
                ;;
            stopall)
                _checkDocker
                . "${MANAGER_DIR}"/bin/docker/stopall
                ;;
            console)
                _checkDocker
                . "${MANAGER_DIR}"/bin/docker/console "${@:2}"
                ;;
            composer)
                _checkDocker
                . "${MANAGER_DIR}"/bin/docker/composer "${@:2}"
                ;;
            cli)
                _checkDocker
                . "${MANAGER_DIR}"/bin/docker/cli "${@:2}"
                ;;
            app:server:add)
                _checkDocker
                . "${MANAGER_DIR}"/bin/docker/console "app:server:add"
                ;;
            app:db:process)
                _checkDocker
                . "${MANAGER_DIR}"/bin/docker/console "app:db:process"
                ;;
            *)
                _help
                ;;
        esac
    else
        case "$1" in
            console)
                php ${MANAGER_DIR}/bin/console "${@:2}"
                ;;
            app:server:add)
                php ${MANAGER_DIR}/bin/console "app:server:add"
                ;;
            app:db:process)
                php ${MANAGER_DIR}/bin/console "app:db:process"
                ;;
            *)
                _help
                ;;
        esac
    fi
fi

